### ISSUE TITLE
OtherPerson's avatar height API

### ISSUE THREAD

**Issue by Narazaka** [VerseEngine/verse-three#2]
I would like to implement a nameplate so that it does not cover the avatar, but I could not find an API to get the height of the OtherPerson's avatar.
Is there such a thing or will it be implemented?

ネームプレートを出すときにアバターにかぶらないようにしたいが、OtherPersonのアバターの高さを取得するAPIがわかりませんでした。
そのようなものはあるor実装されますか？

**Comment by VerseEngine** [comment]
Added display of name labels to text data example

Text dataのexampleに名前ラベルの表示を追加しました


https://github.com/VerseEngine/examples/commit/5ab5d3c50389b288656096766421de0be0683e3a

<img width="1457" alt="name" src="https://github.com/VerseEngine/verse-three/assets/125547575/f7583730-382e-4f24-a98c-11b6464d7966">

**Comment by Narazaka** [comment]
なるほど一旦bounding boxでいけるんですね。ありがとうございます。
