### ISSUE TITLE
OtherPerson's avatar height

### ISSUE THREAD

**Issue by Narazaka** [VerseEngine/verse-three#4]
ネームプレートを出すときにアバターにかぶらないようにしたいという要望について、 #2 で回答をいただきましたが、他プレイヤーのアバター変更が検知出来ないためアバター変更時にネームプレート位置を調整することが出来ません。
OtherPlayerのアバター変更を検知出来るAPIなどがあると良いのではないかと思います。

Regarding the request to prevent the nameplate from covering the avatar, as answered in #2, it is not possible to adjust the position of the nameplate when the avatar changes because it is not possible to detect the avatar change of other players.
It would be good to have an API that can detect other players' avatar changes.

**Comment by VerseEngine** [comment]
ありがとうございます

[EnvAdapter.addOtherPersonAvatarChangedListener](https://github.com/VerseEngine/verse-three/commit/aa81f84f670e0ff7e97dc28a9aa230a93ba5eef5), [OtherPerson.avatar](https://github.com/VerseEngine/verse-three/commit/a2643fc062dd7b2816ec6c6033be2ce8ea3721fe)を追加しました

それを使って、exampleを高さの変更に対応しました
https://github.com/VerseEngine/examples/commit/47134d90901bef943ef82f7e975e14643b0967e4



Thank you.

I added [EnvAdapter.addOtherPersonAvatarChangedListener](https://github.com/VerseEngine/verse-three/commit/aa81f84f670e0ff7e97dc28a9aa230a93ba5eef5), [OtherPerson.avatar](https://github.com/VerseEngine/verse-three/commit/a2643fc062dd7b2816ec6c6033be2ce8ea3721fe)
I used it to make the example support height changes.
https://github.com/VerseEngine/examples/commit/47134d90901bef943ef82f7e975e14643b0967e4
