### ISSUE TITLE
Avatar Not Show in Aframe

### ISSUE THREAD

**Issue by micfio** [VerseEngine/verse-three#5]
Hello i use the sample from examples repository, getstarded Aframe. The Page and the button control are show regular,but when i selected an Avatar this Is Not show in the Page but i visualize It only in the mirror.Where i wrong? Thanks in advances.

**Comment by VerseEngine** [comment]
It is in first person perspective, so it only appears in the mirror.

Verse-three does not implement a third-person perspective, but the three-avatar used in verse-three has an example of switching between TPS/FPS modes, so it is possible to clone verse-three and implement TPS mode.


https://github.com/VerseEngine/three-avatar/blob/5803a28eed2ef9e3811889c27759f2aae0986c20/example/index.html#L106
https://github.com/VerseEngine/three-avatar/blob/5803a28eed2ef9e3811889c27759f2aae0986c20/example/main.js#L123

**Comment by micfio** [comment]
Thanks.I am Not able to produce this code,can provider me the code to modify ? Thanks in advances

**Comment by VerseEngine** [comment]
I am unable to provide an icon that matches this feature.
If you provide me with an icon, I'll program it for you.

* SVG format
* Design that is consistent with other icons
* TPS, FPS 2 patterns of icons are required
* TPS mode is not needed in VR, so just display in 2D
* The icon must be redistributable under a BSD license
* I use Iconoir for my other icons ([LINK](https://github.com/VerseEngine/verse-three-ui/tree/main/src/embed/img))

<img width="306" alt="icons" src="https://github.com/VerseEngine/verse-three/assets/125547575/de9f0108-c78f-4922-920a-8128001035b3">

**Comment by micfio** [comment]
[](url)

**Comment by micfio** [comment]
I produce this images but i dont know if are ok.
![accessibility_fps](https://github.com/VerseEngine/verse-three/assets/20971749/82ca4e22-a6e6-4c26-9fe2-63c31fcafbd0)
![accessibility_tps](https://github.com/VerseEngine/verse-three/assets/20971749/9795a5b3-dffc-4199-bd50-63b86dfc320c)

**Comment by micfio** [comment]
![accessibility_tps](https://github.com/VerseEngine/verse-three/assets/20971749/8f1341b0-4114-4290-b97f-26bb9a627061)
![accessibility_fps](https://github.com/VerseEngine/verse-three/assets/20971749/3b9545ef-8664-4124-b66b-0ebe9447128c)

**Comment by micfio** [comment]
![accessibility_tps](https://github.com/VerseEngine/verse-three/assets/20971749/c88c9951-5a72-4efd-ba61-72c81ce81c67)

**Comment by micfio** [comment]
![accessibility_tps](https://github.com/VerseEngine/verse-three/assets/20971749/43621e8b-2974-4276-a484-0fe28b07c0d3)

**Comment by micfio** [comment]
![circle (1) (1)](https://github.com/VerseEngine/verse-three/assets/20971749/a99372e7-0c93-4f0f-8b3c-c3b6d6fb8327)

**Comment by micfio** [comment]
![circle (2) (1)](https://github.com/VerseEngine/verse-three/assets/20971749/d4e7d427-c8f1-4a93-8f1a-7f62f5329f72)

**Comment by VerseEngine** [comment]
Thanks.
I don't want to include text in the icon because it is too small to read.

If it's difficult to express both FPS and TPS patterns, a single icon symbolizing "viewpoint switching" would be acceptable.

**Comment by micfio** [comment]
![video-camera (1)](https://github.com/VerseEngine/verse-three/assets/20971749/e8e8f8b8-a54c-43ce-95c2-68b662a5c9d9)

**Comment by micfio** [comment]
![video-camera (2)](https://github.com/VerseEngine/verse-three/assets/20971749/2cfbb1ef-6192-422d-a412-7d38ff510d71)

**Comment by micfio** [comment]
This will do represent the third person camera view. I use iconoir. I hope is correct.

**Comment by micfio** [comment]
![video-camera (3)](https://github.com/VerseEngine/verse-three/assets/20971749/5fa74398-423b-4e07-ba3e-7f68a6acf763)

**Comment by VerseEngine** [comment]
Unfortunately, we do not wish to add that button design to the official features.

New version 1.0.6 with added features.
* Custom child elements for 2D UI

Added an EXAMPLE of FPS/TPS switching using this new feature
https://github.com/VerseEngine/verse-three/blob/main/example/tps.html

(This example does not consider switching to VR mode)

https://github.com/VerseEngine/verse-three/assets/125547575/40361ad0-264c-4706-b51c-16bdac2d5c75

**Comment by VerseEngine** [comment]
Implementation using AFrame has been uploaded.
https://codepen.io/hosoi-appland/pen/PoxOLyV
